### PR TITLE
fix: add coinbase wallet connection

### PR DESCRIPTION
**Pull request by jamesbane**
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

### CODE REVIEW

**Comment by apewukong** [comment]
@jamesbane Thanks for your contribution. Currently, there is a build error on Vercel, it's complaining the TS error

image

Was it working locally on your side?

**Comment by jamesbane** [comment]
@apewukong You should deploy uikit first then update uikit version to latest at package.json
That's because ConnectionNames.Walletlink is in uikit

**Comment by apewukong** [comment]
> @jamesbane Thanks for your contribution. Currently, there is a build error on Vercel, it's complaining the TS error
> 
> image
> 
> Was it working locally on your side?

Aha, that makes sense. Out of curiosity, how were you able to test it locally without the updated (published) version?

**Comment by jamesbane** [comment]
I tested on locally by updating node_modules for uikit directly
I build uikit and replace dist folder for apeswapfinance/uikit

**Comment by obiedobo** [comment]
Thanks @jamesbane! I was able to deploy and test this. Working well. Just wanted to see if we can revert the `lock.json` file like we did in the ui kit as well?

**Comment by jamesbane** [comment]
yes
you can revert lock file
And if you change package.json file then lock file will be changed again

**Pull request merged**
